### ISSUE TITLE
Не добавляется расширение

### ISSUE THREAD

**Issue by JonnyUA** [yoannchb-pro/MoodleGPT#1]
Не получается добавить расширение 
![image](https://github.com/yoannchb-pro/MoodleGPT/assets/46706960/7737be45-050c-40b4-9acc-f16d727f2cf8)

**Comment by yoannets** [comment]
Hello, You should export the "extension" directory not all the main directory (https://github.com/yoannchb-pro/MoodleGPT/tree/main/extension). Is it possible to talk english please ?
