### ISSUE TITLE
Moodle Error

### ISSUE THREAD

**Issue by reaperniko** [yoannchb-pro/MoodleGPT#10]
Hey, not sure what I'm doing wrong or my current moodle is not supported. Getting these errors, it will inject but does not answer the questions. 

Not sure if you need a moodlelink? https://moodle.lsua.edu/
![err](https://github.com/yoannchb-pro/MoodleGPT/assets/145908265/c4284d21-abc9-45dd-b319-618c9145a31e)

**Comment by yoannchb-pro** [comment]
Hello, Could you press F12 on the Moodle page then click and console and show me the error ? (Also you can click on the file to see where the error is in the code like in #9 )

**Comment by reaperniko** [comment]
I apologize about the late reply, but here is the error I am getting.

[image: image.png]

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by yoannchb-pro** [comment]
Dont worry but I'm not able to use your link

**Comment by reaperniko** [comment]
I see, yeah most moodle pages would require a log in. So not really sure
how much further we can take this.
Would anything else help?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by yoannchb-pro** [comment]
Just click on the link into the code to show me where the error came from
