### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by bigjohn0203** [yoannchb-pro/MoodleGPT#11]
![Screenshot 2023-10-11 095321](https://github.com/yoannchb-pro/MoodleGPT/assets/147641871/a5e93839-b833-4749-818a-3c71cc8eed6a)

**Comment by yoannchb-pro** [comment]
It's very weird because you get a 404 error from ChatGPT API. Maybe try again and it will work or you api key is not valid or the api is blocked by your network.

**Comment by bigjohn0203** [comment]
API key is valid. I pay for API access. Network does not appear to be the issue. Same error occurs on my network. Is the build outdated? Is the endpoint different now?

**Comment by bigjohn0203** [comment]
I resolved it myself. I just changed the model being used. Does not work with the latest.

**Comment by yaghort** [comment]
I have the same issue which model you used please ? @bigjohn0203

**Comment by Pequie** [comment]
> I resolved it myself. I just changed the model being used. Does not work with the latest.

@bigjohn0203 what model did you use to fix this issue? Please lmk, thanks.

**Comment by yoannchb-pro** [comment]
You can use the extension from the dev branch on which I'm currently working on. The version button should be fixe.
https://github.com/yoannchb-pro/MoodleGPT/tree/dev

**Comment by yoannchb-pro** [comment]
but note the dev version is not tested and could present some bugs and still under devlopement
