### ISSUE TITLE
429 - (Too Many Requests)

### ISSUE THREAD

**Issue by RampantDespair** [yoannchb-pro/MoodleGPT#12]
Any and all questions that I press after injecting MoodleGPT into the current webpage return the error mentioned above.

The error itself states in the console:

> POST https://api.openai.com/v1/chat/completions 429 (Too Many Requests)

> TypeError: Cannot read properties of undefined (reading '0')
    at MoodleGPT.js:1:5703
    at Generator.next (<anonymous>)
    at i (MoodleGPT.js:1:269)
    
And this is the case for any question regardless of formatting.

**Comment by RampantDespair** [comment]
After looking at other issues, the problem lies with my OpenAI account, not the extension itself, my bad.

**Comment by creazyalkan** [comment]
What exactly have you done? I have the same problem

**Comment by RampantDespair** [comment]
> What exactly have you done? I have the same problem

You need to add funds to your OpenAI account, in my case my funds had expired.
So I just added funds to my account and everything works fine now.
