### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by creazyalkan** [yoannchb-pro/MoodleGPT#13]
![image_2023-11-01_182354009](https://github.com/yoannchb-pro/MoodleGPT/assets/45297646/2092a0b8-375e-45b7-bee2-d9192e54713f)
I have this error. I've seen that I'm not the only one, they say I have to solve it by changing the model or something, but I don't know how to do it. Maybe it would be easier if we had to log in openai, instead of putting the key.

**Comment by yoannchb-pro** [comment]
Hello, actually you have a 429 error that mean too many requests. I think you used it too fast or have been used it to much. The only solution is to upgrade your OpenAI subscription or to wait a little bit before OpenAI authorize you back to make request on the API.

**Comment by creazyalkan** [comment]
Ok thanks, I didn't know I needed to pay OpenAI, because I haven't used it either.
