### ISSUE TITLE
MoodleGPT Error and unidentified GPT Model

### ISSUE THREAD

**Issue by HuyLN38** [yoannchb-pro/MoodleGPT#14]
![image](https://github.com/yoannchb-pro/MoodleGPT/assets/123806543/e9c3762c-b853-4600-a082-a8f5bac43e81)

Hello yoannchb-pro, i used to use your extension before and it's great, but recently, i don't know why it having this problem

I really need your help in next 4 hour, hope you can reply me soon :((

**Comment by yoannchb-pro** [comment]
Hello, I saw you closed the issue. Did you found a solution ?
