### ISSUE TITLE
First Time User Errors

### ISSUE THREAD

**Issue by Hephzibah-SO-Cu** [yoannchb-pro/MoodleGPT#15]
Hello yoannchb-pro.
First time user here. And i'm having errors when i try to get it to work

Firstly, 
![Err3](https://github.com/yoannchb-pro/MoodleGPT/assets/93764058/f26899cc-781b-4722-8396-4ab6669e35f9)
The extension shows these errors, when i load the unpacked folder

Then,
when i click on the reload button after getting my API, it says gpt model undefined

and finally, when i run the index.html in the fake-moodle folder and i run my code to inject the extension and click a question
nothing comes up, and when i inspected the element, i found this
![err2](https://github.com/yoannchb-pro/MoodleGPT/assets/93764058/7094a71c-8b5a-49ab-8b0e-b1b4b5c5447f)

Any help or advice that can be given or helped in solving this issues would be deeply appreciated
Thank you in advance

**Comment by yoannchb-pro** [comment]
Hello, I think the problem come from the gpt version. You can try to change it to an other one by your self and see if its working :)

**Comment by SkyBarrier7** [comment]
I have the same problem, how do I change the version?

**Comment by yoannchb-pro** [comment]
You have an input for the version. You can check for the latest on OpenAI website. May be try something like gpt-3

**Comment by Hephzibah-SO-Cu** [comment]
> Hello, I think the problem come from the gpt version. You can try to change it to an other one by your self and see if its working :)

ummm it's not working
TypeError: Cannot read properties of undefined (reading '0')

for gpt-3 the post request gave an error 404 (not found)
for gpt-3.5-turbo the post request gave an error 429 (too many requests)

**Comment by yoannchb-pro** [comment]
When you get a 429 error it's because you have to upgrade your openai account

**Comment by Hephzibah-SO-Cu** [comment]
Hmmm, i see
And how much do i need to fund the openAI account with to get it up and running?
for a couple of tests of course

**Comment by yoannchb-pro** [comment]
Not that much. I have set a limit of 5 dollars on my side.
