### ISSUE TITLE
Unable to find a GPT Model

### ISSUE THREAD

**Issue by evansedeno** [yoannchb-pro/MoodleGPT#18]
Hello,

I'm trying to install the extension but when I type my API Key, my code and I want to refresh the model, it's saying "undefined"

![Capture d’écran du 2023-11-28 17-32-38](https://github.com/yoannchb-pro/MoodleGPT/assets/15571898/28f708e8-b59d-4324-b0ba-3a110a2ef02f)

Do you have a solution ? Thanks !

**Comment by evansedeno** [comment]
When i add "gpt-3.5-turbo" in the field and i inject the extension i got this error in the console: 
![Capture d’écran du 2023-11-28 17-43-13](https://github.com/yoannchb-pro/MoodleGPT/assets/15571898/1bf97a1f-9835-4bd3-99a8-ace9589d7e84)

**Comment by yoannchb-pro** [comment]
Yes actually the button to fecth the latest version is broken you have to check for the current version on OpenAI. But the error 429 is because you have to update your OpenAI subscription.

**Comment by evansedeno** [comment]
Okey, i made the update and it's good, thanks !
