### ISSUE TITLE
MoodleGPT isn't working

### ISSUE THREAD

**Issue by Gabi201265** [yoannchb-pro/MoodleGPT#19]
Good morning, 

I can’t get moodleGPT to work even on the index.html you provided locally. I don’t understand how the code, defined beforehand, can be entered into the moodle test. Could you please help me? 

Have a nice evening, 
Gabriel

**Comment by Gabi201265** [comment]
Hello,

Yes i did it, but i don't know where can I enter the defined code.

Thanks for ur help,
Gabriel

**Comment by yoannchb-pro** [comment]
![image](https://github.com/yoannchb-pro/MoodleGPT/assets/71560747/fc59940b-9728-4473-87e6-52219ed4b9db)
Directly in the extension by clicking on the icon.

**Comment by yoannchb-pro** [comment]
Oui je parle francais aussi. Pour le code c'est juste une maniere d'injecter ou de remove l'injection de ton quizz moodle. Il faut juste le taper sur ton clavier une fois sur ta page moodle pour lancer l'injection. Peu personnes comprennent son principe donc dans la prochaine version je vais le rendre optionel mais je suis trop occuper pour le moment ;(

**Comment by yoannchb-pro** [comment]
Oui, tu mets ce que tu veux dans le code, et après, tu le tapes sur ton clavier lorsque tu es sur le quiz Moodle, et ça devrait fonctionner. Mais oui, je suis très occupé entre mon travail, mes études et ma copine lol. Au final, je reçois beaucoup de mails par rapport à ce projet, et je sais qu'il y a des choses à réparer ou à améliorer, surtout la gestion des erreurs et la réparation du bouton pour récupérer la dernière version de ChatGPT.

**Comment by yoannchb-pro** [comment]
Dit moi si tu ne comprends toujours pas le code

**Comment by Gabi201265** [comment]
Hehe je comprends c'est un projet attrayant. J'ai essayé avec la page fake que tu as créés ton index.html ouvert en local et ça ne fonctionne pas chef. 

Bref ce n'est pas trop grave, c'était pour les exams de fin d'année 🤣

**Comment by yoannchb-pro** [comment]
Si tu arrives toujours pas regarde aussi dans ta console que tu n'as pas d'erreurs provenant de OpenAI sinon tu peux aussi me call sur discord.

**Comment by Gabi201265** [comment]
Envoi moi ton discord en MP (si on peut je suis pas un expert github), ça ne fonctionne pas. Et ça ne génère pas d'erreur dans la console chef.

**Comment by yoannchb-pro** [comment]
yoannchb

**Comment by Gabi201265** [comment]
Je t'ai envoyé une demande chef

**Comment by nassvss** [comment]
cest quoi ton discord stp
