### ISSUE TITLE
Trojan detected : wacatac.b ml

### ISSUE THREAD

**Issue by 1000abc** [yoannchb-pro/MoodleGPT#2]
Defender block the download cause trojan detection for "wacatac.b ml". 

Would you mind to tell more ? 
(I know turning off the anti-virus is the solution)

**Comment by yoannchb-pro** [comment]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=BrowserModifier:Win32/Wacatac.B!ml&ThreatID=291283

As I understand it's due because I can "modify your browser settings".

I think it's because my extension need the storage permission to save the configuration ?

**Comment by yoannchb-pro** [comment]
You can see all the permissions I need here https://github.com/yoannchb-pro/MoodleGPT/blob/main/extension/manifest.json.

**Comment by 1000abc** [comment]
Top I tested it on MAC and **works perfectly you are a genius !**

However it didn't work on a mock up protocred moodle exam. Do you if there is a link with proctorio ?

Furthermore, considering that you have managed to solve the problem of "how to communicate with GPT without it being noticeable," would you be able, based on this extension, to make it read the question, answer it in the background (as is already the case), and ensure that the correct answer to the Moodle quiz appears on a non-suspicious third-party website?

The exam is open book but proctored, so we can access any website. Could you make sure that the answers are hidden among other content on a random website or any other non-suspicious means where we would just need to know where to look to find the correct answer?

By omitting the hover select step, keeping the hidden GPT reasoning, and (new) displaying the answers somewhere (website, Word document, text, or hidden on a fake Google search results page)?

**Comment by yoannchb-pro** [comment]
As I understood you want the extension to be able to display the good answer on other pages for example (just a little bit hidden in some kind of text or somewhere else )?

**Comment by 1000abc** [comment]
**Exactly !** And maybe a way to hide the extension from the chrome list :)

**Comment by yoannets** [comment]
Actually you can hide the extension by your self by clicking on the eye icon (can make it directly in the code). What I can do if you want is a new option that make the response always go in the clipboard so you should able to paste it on any page you want ? 

(it's an other account)

**Comment by 1000abc** [comment]
Would be perfect ! Do you have a link for donations ? If it works with proctorio, let's go !

**Comment by yoannchb-pro** [comment]
Btw what is protorio ? And sure in the next update I will notify you want and add a support link. I will also may be post it directly on the chrome webstore (just need to pay and create an account and it will be done).

**Comment by 1000abc** [comment]
Thank you very much! 

Can you estimate when you will be able to post the update ? 

Maybe putting on chrome would make it very popular and by the way reduce the life of the extension with incoming patchs or school blacklist. Proctorio is a proctor system to record screen during exams.

Yes, let me know, me and my friends totally agreed to pay you for your work (the 2 next weeks are our exams weeks).

**Comment by yoannchb-pro** [comment]
I also have exam comming. I’m gonna try to work on it this week but I have some problem with my api key due to too much request xD. I’ll notify you when it’s done. You are not obligate to give money haha I love when people contribute by giving ideas :). I’m gonna try to publish it on chrome store and to add a mode for autocomplete, clipboard and question to answer (the question will be replaced by the answer)

**Comment by yoannchb-pro** [comment]
Ok it should be done. I published the update and I'm waiting for chrome to review my extension and it should be available on the chrome webstore.

**Comment by yoannchb-pro** [comment]
![image](https://github.com/yoannchb-pro/MoodleGPT/assets/71560747/75a922c8-24bd-4ea3-ad67-f761d2f3076d)

**Comment by 1000abc** [comment]
Amazing, you are a **Big Boss !** Thank's for your work !

Any informations about if it works during proctored exams ?

**Comment by yoannchb-pro** [comment]
Too complicate to know if I can’t try it on my own side :/. If you try and it work tell me. But it should normally work.

**Comment by yoannchb-pro** [comment]
https://chrome.google.com/webstore/detail/moodlegpt/fgiepdkoifhpcgdhbiikpgdapjdoemko?hl=fr
