### ISSUE TITLE
Latest Moodle version

### ISSUE THREAD

**Issue by quindecim15** [yoannchb-pro/MoodleGPT#20]
Greetings,
It does not work with the latest Moodle versions, even with the fake test index.html there's no answer by the API (but the extension commands work). What could I do?

Thank you, have a nice day

**Comment by yoannchb-pro** [comment]
Could you send me a screen of your console when trying to complete a question by clicking on F12 then console please

**Comment by quindecim15** [comment]
Hi, I’ll answer from my GitHub account e-mail to be faster.

I attach the screenshot file you asked for.

I was able to get the extension to work in the index.html test file so there it's ok. But if I create a moodle test (latest version of moodle) the extension doesn't seem to work because when I type in the activation code (which I have set) of the extension no command is activated (not even in the cursor). How can I do this? ￼

**Comment by quindecim15** [comment]
sorry this is the moodle link: Compila in Moduli Google

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Modulo senza titolo


 |

 |

 |



I also attach the screenshot file    Il giovedì 30 novembre 2023 alle ore 19:26:39 CET, yoannchb-pro ***@***.***> ha scritto:  
 
 


I still cant see the image :/. Could you send me the image here and also the link of your moodle page to ensure it match the defined paths into the extension

**Comment by quindecim15** [comment]
Ok let's go there

Inviato da Yahoo Mail su Android 
 
  Il gio, 30 nov, 2023 alle 20:33, ***@***.***> ha scritto:   


You message are kinda broken. Go on the github page it will be better than per mail

**Comment by quindecim15** [comment]
I try here

Moodle Link: https://docs.google.com/forms/d/e/1FAIpQLSe3WNXQgPT7NSbkk10aYS6_1gIxgxHR7FskF-LWO-6_HgK6Rw/viewform?vc=0&c=0&w=1&flr=0&usp=mail_form_link


I attach the screenshot file
![Screenshot 2023-11-30 alle 18 46 33](https://github.com/yoannchb-pro/MoodleGPT/assets/151855693/3f2aec72-fb1a-4435-a46b-770fc547ca78)

**Comment by yoannchb-pro** [comment]
It's because it's not a moodle quiz but a google form this is the reason for

Le jeu. 30 nov. 2023 à 14:41, quindecim15 ***@***.***> a
écrit :

**Comment by yoannchb-pro** [comment]
Not a moodle quiz
