### ISSUE TITLE
Can you explane to me how to make it work?

### ISSUE THREAD

**Issue by Moontrax** [yoannchb-pro/MoodleGPT#22]
look, I am a bit tech savy but I don't understan where to enter the code to activate it

i need this extention to work in the next few hours. LOVE the extention, but I can't make it work

**Comment by Moontrax** [comment]
> look, I am a bit tech savy but I don't understan where to enter the code to activate it
> 
> i need this extention to work in the next few hours. LOVE the extention, but I can't make it work

btw, I give you my word, I'll donate something if this helps me Ace my test

**Comment by Moontrax** [comment]
can you help me out?

**Comment by Moontrax** [comment]
i'm ussing code 911

where do I type this?

**Comment by Moontrax** [comment]
update, I understad the jist of it, bues does it support spanish? 

also it seems I have an error  on the GPT side of things

**Comment by Moontrax** [comment]
For some reason It's not displaying the Answer as it should

**Comment by yoannchb-pro** [comment]
Hello, yes it's supporting any language. can you provide a screen of the error please ? By pressing F12 then console

**Comment by Moontrax** [comment]
Sure, give me a few min

**Comment by Moontrax** [comment]
![IMG_20231219_230305.jpg](https://github.com/yoannchb-pro/MoodleGPT/assets/27937343/c347c84c-d9f0-4cf2-9705-5ab52c90af2c)

**Comment by Moontrax** [comment]
How can I display the Answer? Its now working for me

**Comment by Moontrax** [comment]
The thing is, its not changing the Answer. But it does show on the console some times

**Comment by Moontrax** [comment]
![IMG_20231219_230518.jpg](https://github.com/yoannchb-pro/MoodleGPT/assets/27937343/b834fc97-105c-4e2c-96dc-2238f40a2ada)

This is the question, Im trying it on... It will not change the text to the right Answer

**Comment by yoannchb-pro** [comment]
I think it's due to the prompt. It look like that chatgpt return an invalid answer. I'll try to make a fixe in the futur version if possible. I should start working on it on january.

**Comment by Moontrax** [comment]
Thanks!
