### ISSUE TITLE
Injection not working

### ISSUE THREAD

**Issue by LexTheHexMaster** [yoannchb-pro/MoodleGPT#26]
![image](https://github.com/yoannchb-pro/MoodleGPT/assets/67151799/313f5c17-c56e-4808-b38d-e2f64b1b7fc9)

When i type in my code nothing happens. I will reply instantly.

**Comment by yoannchb-pro** [comment]
I think it’s due to your gpt model. Also please send a pic of the console

**Comment by LexTheHexMaster** [comment]
![Issues · yoannchb-pro_MoodleGPT - Google Chrome 24  1  2024 23_08_33](https://github.com/yoannchb-pro/MoodleGPT/assets/67151799/3f90c951-9865-4bc8-9e93-c573866c46e7)

**Comment by yoannchb-pro** [comment]
And click on console after making test

**Comment by LexTheHexMaster** [comment]
will do

**Comment by LexTheHexMaster** [comment]
I cant start injection process at all. If i put in my code nothing happens

**Comment by LexTheHexMaster** [comment]
https://youtu.be/L3Gp-i6erdU

heres link to video recording, I typed in code several times, also tried to change it and nothing worked

**Comment by LexTheHexMaster** [comment]
When trying to do moodle quiz try it on official site. https://moodle.org/demo . Select Orange school , login info : NAME: student
PASSWORD: moodle . try any quiz. found out that launching quiz locally can cause extention not to work at all.
