### ISSUE TITLE
Injection?

### ISSUE THREAD

**Issue by JelloMan1234** [yoannchb-pro/MoodleGPT#27]
Hey just following up with this project. I open up the test page and press the code number on my keyboard but it doesn't do anything? Just wondering what im doing wrong or I guess i dont understand how to inject it? Is this project still in development?

Edit: got it working. You're amazing. Will be following for future updates and donating

**Comment by yoannets** [comment]
Hello, no the project is ready to use. I think it can be due to your browser. Some browser doesnt allow local file access for extension. I think it's due to that otherwise active the title indication option and check the console by pressing F12->console. Finally, ensure to focus the page by a simple click within before entering your code.

**Comment by JelloMan1234** [comment]
I see. I've tried it on both edge and google. Maybe im not understanding how to inject? I've installed the extension, put my gpt api in and set a code. I try to the test moodle page and just press the keys on my keyboard but nothing else happens. I do click into the page before pressing the keys. The configuration is saved. Could you explain the title indication option? my console also seems to be blank.

**Comment by yoannets** [comment]
I saww you writed this "I see. I've tried it on both edge and google. Maybe im not understanding how to inject? I've installed the extension, put my gpt api in and set a code. I try to the test moodle page and just press the keys on my keyboard but nothing else happens. I do click into the page before pressing the keys. The configuration is saved. Could you explain the title indication option? my console also seems to be blank." but cant see the message anymore. Did you fixed it ?

**Comment by yoannets** [comment]
Oh just saw the edit comment. I'll close the issue thx y :)
