### ISSUE TITLE
Error API Key

### ISSUE THREAD

**Issue by GiovanniFilomeno** [yoannchb-pro/MoodleGPT#28]
Hi, your extension returns the following error: 

{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by yoannchb-pro** [comment]
Hello, did you provide your api key into the extension (it's a mandatory field) ? Also ensure to save you configuration every time you modify the configuration into the extension and to reload the page.
If you need more help please send some screen of the extension too.

**Comment by GiovanniFilomeno** [comment]
Hi, 
thanks for your reply. 
Yes, I tried both the master and the dev repository. With the master, the code is not able to access the API request at all and I see that because in the model it appears "unknown" and the OpenAI API page it appears as "never" used. 
On the contrary, with the dev repository, the code is able to send the API request (I see that in the OpenAI API page) and I am able to "see" the models. 
However, when trying the test, it does not work (yes I activate it, yes I can click on the question)

**Comment by yoannchb-pro** [comment]
Could you provide some screen of your console pelase when you click on a question ?

**Comment by yoannchb-pro** [comment]
Btw don't use the dev version for the moment because I'm currently working back on the extension since today and I have stuff to fixe

**Comment by GiovanniFilomeno** [comment]
<img width="1001" alt="Bildschirmfoto 2024-02-29 um 21 49 26" src="https://github.com/yoannchb-pro/MoodleGPT/assets/19155919/fd7b9e3a-c8bd-46a2-816a-caf1985a7cc4">

**Comment by yoannchb-pro** [comment]
Seems like the error is not from the extension but from your openai api key:
https://help.openai.com/en/articles/6891767-error-code-401-invalid-authentication
