### ISSUE TITLE
No answers are filled

### ISSUE THREAD

**Issue by AKGfra** [yoannchb-pro/MoodleGPT#29]
Hello / bonjour

I put my apikey, code and write "gpt-3.5-turbo-0613" for gpt model. with all the steps checked, in the moodle text html, when i click on questions, nothing seems to made (also test on official moodle website, same problem) the blue circle icon replace my mouse icon 1-2sec and answers arent filled. Do you have any idea?
(im on "questions to answer" mod)

**Comment by AKGfra** [comment]
Here are my console log
![image_2024-03-08_014721175](https://github.com/yoannchb-pro/MoodleGPT/assets/102437575/e1324539-0685-4393-8d2a-ae205be1c330)

Merci / thanks

**Comment by AKGfra** [comment]
Sorry for the multiple message, but i read here : https://www.merge.dev/blog/chatgpt-api-key
that we need to pay now for using api key, is it the problem? Bcz the last

**Comment by yoannchb-pro** [comment]
Hello, there are many issues about this error. It’s due because you have to had money on your account. Check other issues for more informations :)

**Comment by AKGfra** [comment]
Hello , Thanks for your answer

However, I've still an issue. Now its working but the extension answer by replacing the question text, here is an example. When i re-click on the text, the question re-appear.
![image_2024-03-08_133924300](https://github.com/yoannchb-pro/MoodleGPT/assets/102437575/046eadc8-a337-401f-8877-3758a0861196)

Merci pour ton implication

**Comment by AKGfra** [comment]
> Hello, there are many issues about this error. It’s due because you have to had money on your account. Check other issues for more informations :)

**Comment by yoannchb-pro** [comment]
Salut, oui c'est fait exprès. Lors d'un clique tu as la réponse puis si tu re cliques tu as la question à nouveau et ainsi de suite (c'est pour plus de discrétion).

**Comment by AKGfra** [comment]
> Salut, oui c'est fait exprès. Lors d'un clique tu as la réponse puis si tu re cliques tu as la question à nouveau et ainsi de suite (c'est pour plus de discrétion).

**FR** D'accord car dans la partie "Supported questions type" https://github.com/yoannchb-pro/MoodleGPT#supported-questions-type
On voit que le progarmme fill automatiquement les réponses, je ne savais pas que tu as désactivé cette option, qui est je pense tout aussi discrete que le remplacement du texte de la question, car si un controleur passe, et qu'il voit la réponse à la place de la question, c'est plus "cramé" que la proposition que nous montre dans la partie read.me : sauf si il passez sur l'instant meme, il ne peut voir si ça été cocher par moi ou par une ligne de code.

**ENG** Ah okay because in the part "Supported questions type" We see that the progarmme automatically fill the answers, I didnt know that you disabled this option, which is I think just as discrete as replacing the text of the question, because if a controller passes, and that he sees the answer instead of the question, it is more "burned" than the proposal u shows us in the read.me part : unless he passes on the same moment, he can not see if it was checked by me or by a line of code.

Merci / Thanks

**Comment by yoannchb-pro** [comment]
C'est pas désactivé normalement ça devrait l'option par défaut le Autocomplete
