### ISSUE TITLE
Difficult to let the app work

### ISSUE THREAD

**Issue by Ossorr14** [yoannchb-pro/MoodleGPT#31]
I added the extension and inserted the API, I wrote the code and the version of gpt: "gpt-3.5-turbo". Now I opened the moodle test file but nothing happens, when I write the code the console stays empty.

**Comment by carloalbertogiordano** [comment]
Hi, I have the same problem. I've found an issue that I believe is relevant but I do not understand how to make it work

The issue I am referring about is: https://github.com/yoannchb-pro/MoodleGPT/issues/24

**Comment by yoannchb-pro** [comment]
Hi, it’s can be due to many reasons (like your browser not authorizing the extension to access local file). Otherwise you can also check the console by pressing F12 then console. There is also an other and better example you could find in the dev branch and then test part of the read me.

**Comment by yoannchb-pro** [comment]
Go on [this moodle test page](https://school.moodledemo.net/login/index.php) (username: `student`, password: `moodle`) and choose any quiz.

**Comment by Ossorr14** [comment]
Hi, thanks for the answer but I am getting the following errors:


![image](https://github.com/yoannchb-pro/MoodleGPT/assets/163673729/e4566226-b68f-4b21-92be-742cc491df56)

**Comment by yoannchb-pro** [comment]
Ok for this issue please reffer to #12. You have to put some credits on your openai account by setting up a credit card (for example on my side I did set a limit to1$ per month and trust me I never payed more than 0.4$ even if I do a lot of tests)

**Comment by Ossorr14** [comment]
Ok thanks, I will close the issue now, my bad ;-)
