### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by Pogonion** [yoannchb-pro/MoodleGPT#34]
Is this still working as of today? cant seem to get it to work despite it injecting

**Comment by yoannchb-pro** [comment]
Hello, yes it’s still working today. Can you provide more informations about your problem and send also some screen. Ensure to activate logs and title injection and also show me the console by pressing f12 then console.

**Comment by sobalatter** [comment]
Hello. The code doesn't inject in Quiz Review. In early April It did, but now it doesn't. I think moodle changed something. Injecting in review allows to test the accuracy the GPT. The real quiz works in test moodle. I tried on my real institution moodle and test one. The console is blank, so I can't share anything.

**Comment by yoannchb-pro** [comment]
Hello, yes I removed the fact you can inject it in review.

**Comment by Pogonion** [comment]
It ended up being a conflict between other chrome extentions i had enabled, once i disabled them all it started working properly. Thank you very much for the response and the extension

**Comment by sobalatter** [comment]
As a developer it is your choice to decide. However, the preview inject allowed to test some functions with specific questions. I do not rely on moodle test page. For example, this time I needed to test some features, as not titling(inject title), not cursor indicating. I wish all will be working correctly my next quiz.

**Comment by yoannchb-pro** [comment]
Thx. I’ll see if I’ll implement it back :)
If the issues is complete for you then close it please.

**Comment by Pogonion** [comment]
Is there any way to make the code be less than 3 letters?

**Comment by yoannchb-pro** [comment]
Not for now but I can make it in the next update.

**Comment by Pogonion** [comment]
It'd be great if it could be 1-3 characters. Thanks for the response

**Comment by yoannchb-pro** [comment]
To avoid any problems I’ll set it to 2
