### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by Picasa11** [yoannchb-pro/MoodleGPT#38]
Hello, déjà merci pour ton outil ça a l'air super qualitatif :)

Je vais en avoir besoin pour un cours moodle bientôt sur mes cours de communication stratégique à l'uni. J'ai fait quelques test et je crois que j'ai dû faire qqlch de faux j'ai mis API key en la trouvant sur le site de openai direct et une version de chatgpt. mais quans je clique sur la question (qui est en format QCM) je vois la roue de la souris tourné mais rien ne se passe.

que faire ?

merci et belle journée a toi

Leo

**Comment by yoannchb-pro** [comment]
Salut,

Pourrais tu me montré ce que la console t'affiche ?
Tu peux regarder ça en cliquant sur F12 -> Console.
J'ai besoin des messages d'erreurs pour comprendre ce qui ce passe :).

**Comment by Picasa11** [comment]
Alors, après recherches de mon côté…. : j’avais juste pas mis d’argent sur
mon compte api chatgpt haha… donc tout roule ça fonctionne super bien
franchement big bravo c’est un sacré taff (tu mérites bien un petit don tu
vas carry mon examen vendredi pro)

Petit nb : c’est détectable par l’examinateur dans les logs ?

Belle soirée !

Le ven. 31 mai 2024 à 20:28, yoannchb-pro ***@***.***> a
écrit :

**Comment by yoannchb-pro** [comment]
Haha merci ça fait plaisir de voir des gens intéressé par le projet :)
MoodleGPT ne laisse aucune traces. J'ai jamais eu quelqu'un qui se plaint d'avoir été pris avec.
