### ISSUE TITLE
Détection de Moodle

### ISSUE THREAD

**Issue by anaelleplrt** [yoannchb-pro/MoodleGPT#40]
Merci beaucoup !

**Comment by yoannchb-pro** [comment]
Bonjour,

Non je n’ai jamais eu de retour là dessus.
Moodle est juste une plateforme open source pour l’éducation. Il serait complex de détecter un faux clique. Je ne connais pas le fonctionnement en profondeur de celui ci mais l’ayant utilisé personnellement je n’ai jamais eu de problèmes.
