### ISSUE TITLE
"CODE" field, where do I need to get the code and enter it in this field?

### ISSUE THREAD

**Issue by ptyhainfo** [yoannchb-pro/MoodleGPT#7]
I thank you for your great project. I would like to ask you a question. From the picture I've attached, In the "CODE" field, where do I need to get the code and enter it in this field? Please help me explain it. Thank you very much.

![mdgpt](https://github.com/yoannchb-pro/MoodleGPT/assets/137862070/8eb15130-bd17-4be5-b150-77897c3ec432)

**Comment by yoannchb-pro** [comment]
Hello, you can enter whatever you want. It’s just a code that you will need to type on your keyboard to inject the code on the moodle page. It also allow you to remove th cheat :). It’s just like a security if a teacher or someone want to check the moodle page.

**Comment by yoannchb-pro** [comment]
In the futur version of MoodleGPT the code will be not required.
