### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by SkyBarrier7** [yoannchb-pro/MoodleGPT#8]
I encountered a problem when I wanted to try this extension with the following details

![Screenshot 2023-09-04 192902](https://github.com/yoannchb-pro/MoodleGPT/assets/144023439/5f04a3b5-ac98-4f0e-9dc1-7359a166dbbd)

I have topped up my credit balance on OpenAI by $5.00 and the problem still occurs, is there a solution to this problem?

![image](https://github.com/yoannchb-pro/MoodleGPT/assets/144023439/f4683cfb-b745-473c-9928-294afcb860a7)

**_Thank you in advance!_**

**Comment by yoannchb-pro** [comment]
And the date for you grant acess are weird too "Grant 2: 1 october 2024"

**Comment by SkyBarrier7** [comment]
Thank you, it's fixed
