### ISSUE TITLE
Error, while starting GPT by the code

### ISSUE THREAD

**Issue by Lakrity** [yoannchb-pro/MoodleGPT#9]
**Console log:**

```
MoodleGPT.js:1 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at MoodleGPT.js:1:6979
    at HTMLBodyElement.<anonymous> (MoodleGPT.js:1:7110)
```

**Comment by yoannchb-pro** [comment]
Hello, I never saw this error before. Could you give me screen of the console and show me where the error came from the code ?

**Comment by Lakrity** [comment]
![image](https://github.com/yoannchb-pro/MoodleGPT/assets/145117803/fd41b1b5-cb5c-4a29-a929-d7fb8703df1f)
![image](https://github.com/yoannchb-pro/MoodleGPT/assets/145117803/c36cb518-5b75-42f7-ae8e-000205fe6278)

**Comment by yoannchb-pro** [comment]
Ok thx. I don't know why you are getting this error but I will fixe it in the next version. For the moment you can use the version on the dev branch and tell me if it fixe it.
https://github.com/yoannchb-pro/MoodleGPT/tree/dev

**Comment by yoannchb-pro** [comment]
See: https://github.com/yoannchb-pro/MoodleGPT/tree/dev#set-up to set up the extension from the download
